# Generated by Django 5.2.1 on 2025-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('job_description', models.CharField(max_length=200)),
                ('date_posted', models.DateField(auto_now=True)),
            ],
        ),
    ]
